name: smart_vaxx_card_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    firebase_core: '1.3.0'
    firebase_auth: '1.4.1'
    firebase_storage: '^8.1.3'
    cloud_firestore: '^2.2.2'
    firebase_dynamic_links: ^2.0.6
    simple_animations: ^3.1.1
    page_transition: ^2.0.2
    shimmer: ^2.0.0
    timeago: ^3.1.0
    http: ^0.13.3
    flutter_typeahead: ^3.1.3
    image_picker: ^0.8.0+3
    image_cropper: ^1.4.0
    share_plus: ^2.1.4
    path_provider: ^2.0.2
    google_maps_flutter: ^2.0.6
    json_annotation: ^4.0.1
    country_code_picker: ^2.0.2
    location: ^4.3.0
    provider: ^5.0.0
    google_sign_in: ^5.0.4
    font_awesome_flutter: ^9.1.0
    google_fonts: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.0.4
    flutter_native_splash: ^1.2.0

flutter_native_splash:
    color: '#050505'
    image: images/vaccine-icon.png
    android: true
    ios: true

flutter:
    uses-material-design: true

    assets:
        - images/
