on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build-and-test-apk: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: fwilhe2/setup-kotlin@main
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    - run: flutter pub get
    - run: flutter build apk -v

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        token: ${{ secrets.REPO_SECRET }}
        commit: main
        tag: v1.0.${{ github.run_number }}

